[workspace]
members = [
	"apps/agent",
	"apps/control",
	"apps/frontend",
	"package/hw-info",
	"package/containers",
	"package/prisma",
	"package/smithy-common",
	"package/geth-agent-client",
	"package/geth-agent-server",
	"tools/prisma-cli",
]
resolver = "2"